version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=${DATABASE_URL:-sqlite:///local.db}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379}
    volumes:
      - .:/app
      - /app/__pycache__
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data: